version: "3"

services:
  nas-tools:
    image: jxxghp/nas-tools:latest
    hostname: nas-tools
    volumes:
       # 冒号左边请修改为你想保存配置的路径
      - /share/CACHEDEV2_DATA/nasTool/nastool:/config
       # 这里建议设置一级目录
      - /share/CACHEDEV2_DATA/nasTool/Downloads:/downloads
    environment:
      - PUID=1000
      - PGID=0
      - UMASK=0
      - NASTOOL_AUTO_UPDATE=false     # 自动升级，需要自动升级就把false改为true
    restart: always
    #network_mode: host
    container_name: nas-tools
    ports:
      - 3000:3000
    networks:
      - t3net

  qbittorrent:
    image: linuxserver/qbittorrent:amd64-latest
    volumes:
      - /share/CACHEDEV2_DATA/nasTool/qbit:/config
      - /share/CACHEDEV2_DATA/nasTool/Downloads:/downloads
    environment:
      - PUID=1000
      - PGID=0
      - TZ=Aisa/Shanghai
      - WEBUI_PORT=8080
    restart: always
    #network_mode: host
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    container_name: qbittorrent
    networks:
      - t3net


  jackett:
    image: linuxserver/jackett:latest
    hostname: jackett
    container_name: jackett
    #network_mode: host
    environment:
      - PUID=1000
      - PGID=0
      - AUTO_UPDATE=true #optional
    volumes:
      # 配置文件夹
      - /share/CACHEDEV2_DATA/nasTool/jackett:/config
      # 这里和nastools设置同样的  /Download
      - /share/CACHEDEV2_DATA/nasTool/Downloads:/downloads

    ports:
      - 9117:9117
    networks:
      - t3net


  jellyfin:
    image: linuxserver/jellyfin:latest
    hostname: jellyfin
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Aisa/Shanghai
      - LANG=en_US.UTF-8
      - JELLYFIN_PublishedServerUrl=nas-tools #optional
    privileged: true
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /share/CACHEDEV2_DATA/nasTool/jellyfin/config:/config
      - /share/CACHEDEV2_DATA/nasTool/jellyfin/cache:/cache
      - /share/CACHEDEV2_DATA/nasTool/Downloads/Link/movies:/data/movies
      - /share/CACHEDEV2_DATA/nasTool/Downloads/Link/comic/动漫:/data/comic
      - /share/CACHEDEV2_DATA/nasTool/Downloads/Link/comic/tvplay:/data/tvplay
      - /share/CACHEDEV2_DATA/nasTool/Downloads/Link/comic/other:/data/other
    ports:
      - 8096:8096
      - 8920:8920      #optional
      #- 7359:7359/udp #optional
      #- 1900:1900/udp #optional
    restart: always
    networks:
      - t3net


networks:
   t3net:
     external: true
     name: nastool